---

- name: "[WORDPRESS] - update cache"
  apt:
    update_cache: yes
  become: yes

- name: "[WORDPRESS] - install PACKAGES FOR  LAMP"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ package_name }}"

- name: "[WORDPRESS] - Start apache2 mysql"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mysql
